name: ci
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: my-image
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker buildx build . -o type=tar,dest=image.tar
      - name: Push image to Caasis
        run: |-
          gzip -c image.tar > a
          #| curl -L --data-binary @-
          echo https://api.caasis.cloud/new | gh pr comment --delete-last ${{ github.head_ref }} -F -
        if: ${{ github.head_ref }}
